# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [37]:
import numpy as np

lst = [1,2,3,4,5,6,7,8]
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [38]:
[i**2 for i in lst]

[1, 4, 9, 16, 25, 36, 49, 64]

In [39]:
arr = np.array(lst)
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [40]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False, False])

In [41]:
arr[mask]

array([1, 2, 3])

In [42]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
arr[:3,]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [44]:
arr1 = np.random.uniform(0, 20, size=(4, 7))
(arr1 - arr1.min()) / (arr1.max()- arr1.min())

array([[0.38158028, 0.87627059, 0.18802778, 0.17737119, 0.96318518,
        0.1808226 , 0.41560192],
       [0.38157946, 0.51044997, 0.53976002, 0.80581357, 0.13620125,
        0.82885762, 0.58653371],
       [0.        , 0.71759982, 1.        , 0.06800896, 0.36954279,
        0.58651155, 0.00948093],
       [0.46932633, 0.74697514, 0.65840498, 0.08060754, 0.00779261,
        0.76756525, 0.49089985]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [45]:
arr2 = np.random.randint(0,10,size=(8,10))
arr2

array([[6, 3, 7, 8, 7, 9, 3, 2, 2, 1],
       [2, 8, 9, 2, 5, 7, 0, 6, 3, 7],
       [5, 0, 5, 3, 2, 7, 7, 8, 1, 1],
       [1, 5, 8, 8, 0, 9, 8, 6, 4, 9],
       [9, 5, 0, 3, 6, 3, 1, 6, 8, 4],
       [6, 8, 5, 8, 5, 9, 7, 8, 7, 4],
       [9, 7, 2, 4, 9, 3, 3, 3, 2, 7],
       [4, 6, 5, 6, 7, 5, 6, 4, 7, 0]])

In [46]:
str_col = arr2.sum(axis=1)
arr2[str_col == str_col.min()]

array([[5, 0, 5, 3, 2, 7, 7, 8, 1, 1]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [47]:
arr31 = np.random.randint(0,10,size=(1,10))
arr32 = np.random.randint(0,10,size=(1,10))
print(f"array 3.1:\n{arr31}\narray 3.2:\n{arr32}")

formula = np.sqrt(((arr31 - arr32) ** 2).sum())
print(f"Answer:\n{formula}")

array 3.1:
[[4 8 6 7 8 7 9 8 2 9]]
array 3.2:
[[8 5 5 3 2 3 2 1 4 2]]
Answer:
15.652475842498529


In [48]:
print(f"Second method:\n{np.linalg.norm(arr31-arr32)}")

Second method:
15.652475842498529


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [49]:
# A * X * B = -C
# X = 
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}\n")

otvet = np.linalg.inv(a) @ (-c) @ np.linalg.inv(b)
print(f"Answer:\n{otvet}")

a:
[[-1  2  4]
 [-3  1  2]
 [-3  0  1]]
b:
[[ 3 -1]
 [ 2  1]]
c:
[[ 7 21]
 [11  8]
 [ 8  4]]

Answer:
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [19]:
import numpy as np

fileName = 'minutes_n_ingredients.txt'
dataType = ([('id', 'i2'),('minutes', '|S2'),('n_ingredients', 'i2')])
data = np.loadtxt(fileName, np.dtype(np.int32))
data

ValueError: Wrong number of columns at line 15712

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.