# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [10]:
import numpy as np

lst = [1,2,3,4,5,6,7,8]
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [11]:
[i**2 for i in lst]

[1, 4, 9, 16, 25, 36, 49, 64]

In [19]:
arr = np.array(lst)
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [26]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False, False])

In [27]:
arr[mask]

array([1, 2, 3])

In [31]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
arr[:3,]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [46]:
arr1 = np.random.uniform(0, 20, size=(4, 7))
(arr1 - arr1.min()) / (arr1.max()- arr1.min())

array([[0.        , 0.36094965, 0.93997492, 0.10694   , 0.07673292,
        1.        , 0.08918559],
       [0.32770834, 0.46200626, 0.15093751, 0.67567634, 0.59940638,
        0.73197853, 0.45228573],
       [0.97704765, 0.46274898, 0.07548768, 0.52054036, 0.19233138,
        0.76336226, 0.47195073],
       [0.89800861, 0.34407878, 0.17241379, 0.11118686, 0.7624887 ,
        0.81255411, 0.34578949]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [56]:
arr2 = np.random.randint(0,10,size=(8,10))
arr2

array([[6, 2, 5, 2, 6, 1, 5, 5, 1, 3],
       [7, 1, 8, 9, 9, 7, 6, 4, 3, 4],
       [7, 5, 1, 8, 8, 3, 8, 7, 8, 3],
       [0, 2, 5, 4, 0, 8, 9, 0, 4, 3],
       [8, 6, 7, 1, 9, 3, 5, 3, 4, 5],
       [1, 5, 2, 2, 6, 2, 2, 5, 7, 0],
       [3, 8, 9, 9, 8, 6, 4, 9, 6, 7],
       [6, 4, 6, 7, 9, 4, 5, 1, 6, 1]])

In [66]:
str_col = arr2.sum(axis=1)
arr2[str_col == str_col.min()]

array([[1, 5, 2, 2, 6, 2, 2, 5, 7, 0]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [90]:
arr31 = np.random.randint(0,10,size=(1,10))
arr32 = np.random.randint(0,10,size=(1,10))
print(f"array 3.1:\n{arr31}\narray 3.2:\n{arr32}")

formula = np.sqrt(((arr31 - arr32) ** 2).sum())
print(f"Answer:\n{formula}")

array 3.1:
[[4 3 2 9 0 6 1 7 0 7]]
array 3.2:
[[9 2 9 2 8 8 8 8 6 8]]
Answer:
16.703293088490067


In [91]:
print(f"Second method:\n{np.linalg.norm(arr31-arr32)}")

Second method:
16.703293088490067


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [101]:
# A * X * B = -C
# X = 
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}\n")

otvet = np.linalg.inv(a) @ (-c) @ np.linalg.inv(b)
print(f"Answer:\n{otvet}")

a:
[[-1  2  4]
 [-3  1  2]
 [-3  0  1]]
b:
[[ 3 -1]
 [ 2  1]]
c:
[[ 7 21]
 [11  8]
 [ 8  4]]

Answer:
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.