# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [19]:
import numpy as np

lst = [1,2,3,4,5,6,7,8]
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [20]:
[i**2 for i in lst]

[1, 4, 9, 16, 25, 36, 49, 64]

In [21]:
arr = np.array(lst)
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [22]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False, False])

In [23]:
arr[mask]

array([1, 2, 3])

In [24]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
arr[:3,]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [26]:
arr1 = np.random.uniform(0, 20, size=(4, 7))
(arr1 - arr1.min()) / (arr1.max()- arr1.min())

array([[0.18784743, 0.3885215 , 0.53981732, 0.16776857, 0.14982726,
        0.81885817, 0.97174737],
       [0.80491661, 0.99012333, 0.42661524, 0.97583111, 0.68982954,
        0.78274338, 0.24040235],
       [0.33296943, 0.        , 0.53923526, 1.        , 0.52681047,
        0.93468657, 0.47614626],
       [0.68587674, 0.43903494, 0.37454642, 0.10824541, 0.31988197,
        0.57006494, 0.53598996]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [27]:
arr2 = np.random.randint(0,10,size=(8,10))
arr2

array([[1, 5, 9, 7, 7, 1, 9, 9, 2, 8],
       [8, 2, 8, 8, 4, 1, 3, 2, 5, 7],
       [5, 7, 2, 4, 0, 3, 8, 9, 6, 4],
       [3, 5, 7, 0, 5, 4, 9, 0, 4, 3],
       [1, 4, 0, 0, 0, 9, 9, 6, 9, 7],
       [0, 2, 5, 9, 0, 8, 6, 5, 4, 8],
       [6, 5, 7, 4, 1, 3, 8, 2, 0, 0],
       [9, 6, 2, 2, 9, 8, 5, 4, 5, 6]])

In [28]:
str_col = arr2.sum(axis=1)
arr2[str_col == str_col.min()]

array([[6, 5, 7, 4, 1, 3, 8, 2, 0, 0]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [29]:
arr31 = np.random.randint(0,10,size=(1,10))
arr32 = np.random.randint(0,10,size=(1,10))
print(f"array 3.1:\n{arr31}\narray 3.2:\n{arr32}")

formula = np.sqrt(((arr31 - arr32) ** 2).sum())
print(f"Answer:\n{formula}")

array 3.1:
[[8 4 0 2 5 6 9 9 1 0]]
array 3.2:
[[9 5 0 6 0 5 0 5 5 3]]
Answer:
12.884098726725126


In [30]:
print(f"Second method:\n{np.linalg.norm(arr31-arr32)}")

Second method:
12.884098726725126


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [31]:
# A * X * B = -C
# X = 
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}\n")

otvet = np.linalg.inv(a) @ (-c) @ np.linalg.inv(b)
print(f"Answer:\n{otvet}")

a:
[[-1  2  4]
 [-3  1  2]
 [-3  0  1]]
b:
[[ 3 -1]
 [ 2  1]]
c:
[[ 7 21]
 [11  8]
 [ 8  4]]

Answer:
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [5]:
import numpy as np


task01 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1, max_rows = 5)
print(f"[Task 01] Answer:\n\nThe first 5 lines of the array:\n{task01}")

[Task 01] Answer:

The first 5 lines of the array:
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [15]:
task02 = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',',skiprows=1,usecols=(1,2))
print(
    f"[Task 02] Answer:\n\nMean: [{task02[:,0].mean()}, {task02[:,1].mean()}]\nMinimum: {task02.min(axis=0)}\nMaximum: {task02.max(axis=0)} \nMedian: {np.median(task02, axis=0)}"
    )

[Task 02] Answer:

Mean: [21601.00169, 9.05528]
Minimum: [0 1]
Maximum: [2147483647         39] 
Median: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [20]:
task03 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)
forQ = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)
q = np.quantile(forQ, 0.75, axis=0)
print(f"[Task 03] Answer:\n\n{task03[forQ < q]}")
#print(q)

[Task 03] Answer:

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [24]:
task04 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)
arrForZeroVal = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)

# np.place(arr, mask, vals)
np.place(task04[:,1], task04[:,1]==0, 1)
print(f"[Task 04] Answer: {np.size(arrForZeroVal[arrForZeroVal==0])}")

[Task 04] Answer: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [27]:
task05 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=0)

# np.unique(arr, , , , axis)
print(f"[Task 05] Answer: {np.size(np.unique(task05))}")

[Task 05] Answer: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [34]:
task06 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=2)

print(task06)
print(f"[Task 06] Answer: \n\nNumber of values: {np.size(np.unique(task06))}\nAll different values of a variable: \n{np.unique(task06)}")

[16  7  6 ... 15  4 14]
[Task 06] Answer: 

Number of values: 37
All different values of a variable: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [67]:
#array of minutes
task08 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)

np.place(task08, task08==0, 1)
# answer=ingredients/minutes
ans = task06/task08
print(f"[Task 08] Answer:\n\n{ans}\nMax: {max(ans)}")

[Task 08] Answer:

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
Max: 24.0


In [74]:
# delete it
x = np.array([1,1,0,2,0,5,3,8,2,4,0,9]).reshape(4,3)

print(f"{x}\n\n{x[~(x==0).any(1)]}\n\n{x[:,2]/x[:,1]}")



[[1 1 0]
 [2 0 5]
 [3 8 2]
 [4 0 9]]

[[3 8 2]]

[0.    inf 0.25  inf]


/var/folders/lf/d2lsgyp97ql5m98sdnhnmftm0000gn/T/ipykernel_832/3629250627.py:3: RuntimeWarning: divide by zero encountered in true_divide
  print(f"{x}\n\n{x[~(x==0).any(1)]}\n\n{x[:,2]/x[:,1]}")


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.