# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

In [1]:
import numpy as np

lst = [1,2,3,4,5,6,7,8]
lst

[1, 2, 3, 4, 5, 6, 7, 8]

In [2]:
[i**2 for i in lst]

[1, 4, 9, 16, 25, 36, 49, 64]

In [3]:
arr = np.array(lst)
arr ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [4]:
mask = arr < 4
mask

array([ True,  True,  True, False, False, False, False, False])

In [5]:
arr[mask]

array([1, 2, 3])

In [6]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
arr[:3,]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [8]:
arr1 = np.random.uniform(0, 20, size=(4, 7))
(arr1 - arr1.min()) / (arr1.max()- arr1.min())

array([[0.78692876, 0.61654644, 0.18863573, 0.83321927, 0.77109375,
        0.66736238, 0.7975066 ],
       [0.37151038, 0.21547551, 0.62043075, 0.46447621, 0.21400082,
        0.88940178, 0.96630287],
       [0.22381617, 0.73779681, 0.8085442 , 0.83553378, 0.16448572,
        0.9562833 , 0.99696322],
       [0.68477994, 0.4422416 , 0.        , 0.26210221, 0.5921566 ,
        1.        , 0.09603245]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [9]:
arr2 = np.random.randint(0,10,size=(8,10))
arr2

array([[7, 0, 8, 1, 9, 4, 9, 6, 9, 8],
       [6, 1, 3, 7, 8, 7, 0, 1, 1, 8],
       [7, 3, 9, 7, 8, 6, 1, 1, 8, 2],
       [6, 3, 0, 3, 1, 5, 5, 3, 4, 5],
       [7, 4, 4, 2, 6, 1, 2, 1, 0, 3],
       [2, 2, 0, 4, 3, 0, 9, 3, 0, 4],
       [0, 7, 7, 1, 0, 2, 9, 7, 5, 1],
       [7, 2, 0, 7, 6, 6, 1, 7, 6, 2]])

In [10]:
str_col = arr2.sum(axis=1)
arr2[str_col == str_col.min()]

array([[2, 2, 0, 4, 3, 0, 9, 3, 0, 4]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [11]:
arr31 = np.random.randint(0,10,size=(1,10))
arr32 = np.random.randint(0,10,size=(1,10))
print(f"array 3.1:\n{arr31}\narray 3.2:\n{arr32}")

formula = np.sqrt(((arr31 - arr32) ** 2).sum())
print(f"Answer:\n{formula}")

array 3.1:
[[3 6 9 4 5 6 6 3 0 1]]
array 3.2:
[[1 5 1 2 6 7 4 9 9 8]]
Answer:
15.652475842498529


In [12]:
print(f"Second method:\n{np.linalg.norm(arr31-arr32)}")

Second method:
15.652475842498529


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [13]:
# A * X * B = -C
# X = 
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}\n")

otvet = np.linalg.inv(a) @ (-c) @ np.linalg.inv(b)
print(f"Answer:\n{otvet}")

a:
[[-1  2  4]
 [-3  1  2]
 [-3  0  1]]
b:
[[ 3 -1]
 [ 2  1]]
c:
[[ 7 21]
 [11  8]
 [ 8  4]]

Answer:
[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [14]:
import numpy as np


task01 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter = ',', skiprows = 1, max_rows = 5)
print(f"[Task 01] Answer:\n\nThe first 5 lines of the array:\n{task01}")

[Task 01] Answer:

The first 5 lines of the array:
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [15]:
task02 = np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32, delimiter=',',skiprows=1,usecols=(1,2))
print(f"[Task 02] Answer:\n\nMean: [{task02[:,0].mean()}, {task02[:,1].mean()}]\nMinimum: {task02.min(axis=0)}\nMaximum: {task02.max(axis=0)} \nMedian: {np.median(task02, axis=0)}")

[Task 02] Answer:

Mean: [21601.00169, 9.05528]
Minimum: [0 1]
Maximum: [2147483647         39] 
Median: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [16]:
task03 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)
forQ = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)
q = np.quantile(forQ, 0.75, axis=0)
print(f"[Task 03] Answer:\n\n{task03[forQ < q]}")
#print(q)

[Task 03] Answer:

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [371794     35      8]
 [ 43407     35      7]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [17]:
task04 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)
arrForZeroVal = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)

# np.place(arr, mask, vals)
np.place(task04[:,1], task04[:,1]==0, 1)
print(f"[Task 04] Answer: {np.size(arrForZeroVal[arrForZeroVal==0])}")

[Task 04] Answer: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [18]:
task05 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=0)

# np.unique(arr, , , , axis)
print(f"[Task 05] Answer: {np.size(np.unique(task05))}")

[Task 05] Answer: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [19]:
task06 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=2)

# np.size - кол-во, np.unique - уникальное значение из массива
print(f"[Task 06] Answer: \n\nNumber of values: {np.size(np.unique(task06))}\nAll different values of a variable: \n{np.unique(task06)}")

[Task 06] Answer: 

Number of values: 37
All different values of a variable: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [20]:
# task06 - кол-во ингредиентов 
task07 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)[task06<=5]
print(f"[Task 07] Answer:\n\n{task07}")

[Task 07] Answer:

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [21]:
# НЕ ПОНЯЛ НЕ ПОНЯЛ НЕ ПОНЯЛ НЕ ПОНЯЛ НЕ ПОНЯЛ НЕ ПОНЯЛ НЕ ПОНЯЛ НЕ ПОНЯЛ 

#array of minutes
task08 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)

# np.place(task08, task08==0, 1)
# answer=ingredients/minutes
ans = task06/task08
print(f"[Task 08] Answer:\n\n{ans}\nMax: {max(ans)}")

[Task 08] Answer:

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
Max: inf


/var/folders/lf/d2lsgyp97ql5m98sdnhnmftm0000gn/T/ipykernel_5009/1476784174.py:8: RuntimeWarning: divide by zero encountered in true_divide
  ans = task06/task08


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [22]:
task09 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)

task09_01 = task09[task09[:, 1].argsort()[::-1]][:100, :]
print(f"[Task 09] Answer: {task09_01[:, 2].mean(axis=0)}")


[Task 09] Answer: 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [23]:
task10 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1)

# np.replace.choice(a, size:int, replace:boolean, p)
print(f"[Task 10] Answer:\n\n{task10[np.random.choice(task10.shape[0], 10, replace=False)]}")

[Task 10] Answer:

[[349575     25     11]
 [193175     40      9]
 [216416     40     14]
 [325029     30      9]
 [163787     25      8]
 [302103     20     10]
 [457095    110      8]
 [431870     13      5]
 [490031     50      6]
 [492528    270     10]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [24]:
task11 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=2)

# (кол-во рец ниже ср / кол-во всех) * 100
task11_1 = np.size(task11[task11<task11.mean()]) / np.size(task11) * 100
print(f"[Task 11] Answer: {task11_1} %")

[Task 11] Answer: 58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [25]:
task12 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1) # id,m,n
task12_1 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1) # m
task12_2 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=2) # n

task12_3 = np.hsplit(np.where((task12_1 <= 20)&(task12_2 <= 5), 1, 0), np.size(task12_1))
print(f"[Task 12] Answer: \n\n{np.append(task12, task12_3, axis=1)}")

[Task 12] Answer: 

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [26]:
task13 = np.where((task12_1 <= 20)&(task12_2 <= 5), 1, 0)

# (кол-во простых / кол-во всех) * 100
print(f"[Task 13] Answer: {np.size(task13[task13==1]) / np.size(task13) * 100} %")

[Task 13] Answer: 9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [27]:
task14 = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=(0,1))
task14_SecCol = np.loadtxt('minutes_n_ingredients.csv', dtype = np.int32, delimiter=',', skiprows=1, usecols=1)
# условие, 1-short(-inf;10), 2-avarage(10;20), 3-long(20;+inf)
task14_usl = np.where((task14_SecCol <= 10), 1, (np.where((task14_SecCol > 10)&(task14_SecCol <= 20), 2, 3)))
# замена значений столбца id на 1,2,3
task14_zam = np.insert(task14, 0, task14_usl, axis=1)
task14_1 = task14_zam[task14_usl==1][:12466,:] # short
task14_2 = task14_zam[task14_usl==2][:12466,:] # avarage
task14_3 = task14_zam[task14_usl==3][:12466,:] # long
print(f"[Task 14] Answer: \n\n{np.stack([task14_1,task14_2, task14_3])}")
# print(f"Short cooking time:\n\n{task14_1}\n\nAvarage cooking time:\n\n{task14_2}\n\nLong cooking time:\n\n{task14_3}")

[Task 14] Answer: 

[[[     1  94746     10]
  [     1  67660      5]
  [     1 366174      7]
  ...
  [     1 420725      5]
  [     1   4747      0]
  [     1 370915      5]]

 [[     2  33941     18]
  [     2 446597     15]
  [     2  74205     20]
  ...
  [     2 230115     20]
  [     2 496131     20]
  [     2 365818     20]]

 [[     3 127244     60]
  [     3  23891     25]
  [     3 157911     60]
  ...
  [     3  68428     70]
  [     3 312995   1445]
  [     3  93651    240]]]
